- name: 'linux : install snmp'
  become: true
  package:
    name: '{{ item }}'
  with_items:
    - '{{ snmp_packages }}'
  register: check_install
  check_mode: true

- block: 
  - name: 'linux : started snmp'
    become: true
    service:
      name: '{{ snmp_service_name }}'
      state: started

  - name: enabled snmp
    become: true
    service:
        name: "{{ snmp_service_name }}"
        enabled: true   


  when: check_install.changed