    - name: 'linux : stopped snmp'
      become: true
      service:
        name: '{{ snmp_service_name }}'
        state: stopped

    - name: Restore Config
      become: true
      copy:
        remote_src: yes
        src: '{{ snmp_config_backup }}'
        dest: '{{ snmp_config }}'

    - name: 'linux : started snmp'
      become: true
      service:
        name: '{{ snmp_service_name }}'
        state: started